remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs

title: Hybrid Cloud Patterns
description: It's patterns all the way down
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hybrid-cloud-patterns.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

logo: images/logos/animated-100.gif

permalink: pretty
exclude: [ "node_modules/", "*.gemspec", "cheat.md", "LICENSE.txt", "README.md" ]

color_scheme: patterns

# Enable or disable heading anchors
heading_anchors: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit on GitHub"
gh_edit_repository: "https://github.com/hybrid-cloud-patterns/docs" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_source: "" # the source that your files originate from
gh_edit_view_mode: "blob" # "tree" or "edit" if you want the user to jump into the editor immediately


aux_links:
  "Validated Patterns":
    - "https://redhat-gitops-patterns.io"
  "Blog":
    - "/blog"

## Blog

# Plugins
plugins:
  - jekyll-paginate
  
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

#permalink: /blog/:year/:day/:title #/:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Australia/Melbourne # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


words_per_minute: 200
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        overlay_image: blue-yellow-banner-thin.jpg
        caption: "Photo credit: [WeGraphics](http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/)"
      sidebar:
        tagcloud: true
