remote_theme: pmarsceill/just-the-docs

title: Hybrid Cloud Patterns
description: Patterns all the way down
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://hybrid-cloud-patterns.io" # the base hostname & protocol for your site, e.g. http://example.com

logo: images/atlas-logo-png--320.png

permalink: pretty
exclude: [ "node_modules/", "*.gemspec", "cheat.md", "LICENSE.txt", "README.md" ]

# Enable or disable heading anchors
heading_anchors: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit on GitHub"
gh_edit_repository: "https://github.com/hybrid-cloud-patterns/docs" # the github URL for your repo
gh_edit_branch: "gh_pages" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


aux_links:
  "Images":
    - "https://quay.io/organization/hybridcloudpatterns"
